name: Continuous Integration

on: 
  push: 
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Server
        uses: docker/build-push-action@v4
        with:
          context: ./metaverse
          file: ./metaverse/Docker/Dockerfile.server
          push: true
          tags: pawanhfl/gathertown-server:${{ env.SHORT_SHA }}

      - name: Build and push Websocket
        uses: docker/build-push-action@v4
        with:
          context: ./metaverse
          file: ./metaverse/Docker/Dockerfile.ws
          push: true
          tags: pawanhfl/gathertown-server:${{ env.SHORT_SHA }}

      - name: clone system-ops , update and push
        env: 
          PAT: ${{ secrets.MY_PERSONAL_GITHUB_TOKEN }}
        run: |
          git clone https://github.com/spawan02/system_ops.git
          cd system_ops
          sed -i "s|image: pawanhfl/gathertown-server:.*|image: pawanhfl/gathertown-server:${{ env.SHORT_SHA }}|g" metaverse/server.yml
          sed -i "s|image: pawanhfl/gathertown-ws:.*|image: pawanhfl/gathertown-ws:${{ env.SHORT_SHA }}|g" metaverse/ws.yml
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add metaverse/server.yml metavarse/ws.yml 
          git commit -m "Update images to new tags: ${{ env.SHORT_SHA }}"
          git push https://${PAT}@github.com/spawan02/system_ops.git main